# Generated by Django 3.2.14 on 2022-08-12 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("logger_name", models.CharField(max_length=100)),
                ("level", models.CharField(blank=True, max_length=255)),
                ("line", models.CharField(blank=True, max_length=255)),
                ("function", models.CharField(blank=True, max_length=255)),
                ("pathname", models.CharField(blank=True, max_length=1024)),
                ("http_method", models.CharField(blank=True, max_length=128)),
                ("request_url", models.CharField(blank=True, max_length=1024)),
                ("exception_type", models.CharField(blank=True, max_length=256)),
                ("exception_value", models.CharField(blank=True, max_length=512)),
                ("stack_trace", models.TextField(blank=True, null=True)),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Errors",
                "verbose_name_plural": "Log Errors",
                "ordering": ("-date",),
            },
        ),
    ]
