# Generated by Django 3.2.14 on 2022-08-12 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("log_errors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="logerror",
            table="log_errors_django",
        ),
    ]
