# Generated by Django 3.2.14 on 2022-08-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("log_errors", "0003_alter_logerror_line"),
    ]

    operations = [
        migrations.AlterField(
            model_name="logerror",
            name="line",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
